graph:
  edges:
  - - SN-like
    - SN-gen
  - - SN-like
    - TDE
  - - SN-gen
    - SN
  - - SN-gen
    - SN Ia-gen
  - - SN-gen
    - CC
  - - SN Ia-gen
    - SN Ia
  - - SN Ia-gen
    - SN Ia-91T
  - - SN Ia-gen
    - SN Ia-91bg-like
  - - SN Ia-gen
    - SN Ia-CSM
  - - SN Ia-gen
    - SN Ia-SC
  - - SN Ia-gen
    - SN Ia-pec
  - - SN Ia-gen
    - SN Iax
  - - CC
    - SN II-gen
  - - CC
    - SN Ib/c-gen
  - - CC
    - SLSN-I
  - - SN II-gen
    - SN IIn-like
  - - SN II-gen
    - SN II-like
  - - SN Ib/c-gen
    - SN Ib/c
  - - SN Ib/c-gen
    - SN Ib-gen
  - - SN Ib/c-gen
    - SN Ic-gen
  - - SN Ib-gen
    - SN Ib-pec
  - - SN Ib-gen
    - SN Ibn
  - - SN Ib-gen
    - SN Ib
  - - SN Ic-gen
    - SN Ic-BL
  - - SN Ic-gen
    - SN Ic-Ca-rich
  - - SN Ic-gen
    - SN Ic-pec
  - - SN Ic-gen
    - SN Icn
  - - SN Ic-gen
    - SN Ic
  - - SN IIn-like
    - SLSN-II
  - - SN IIn-like
    - SN IIn
  - - SN II-like
    - SN II-pec
  - - SN II-like
    - SN IIb
  - - SN II-like
    - SN IIL
  - - SN II-like
    - SN IIP
  - - SN II-like
    - SN II
  height: 4
  root: SN-like
  vertices:
  - SLSN-I
  - SLSN-II
  - SN
  - SN II
  - SN II-pec
  - SN IIb
  - SN IIn
  - SN Ia
  - SN Ia-91T
  - SN Ia-91bg-like
  - SN Ia-CSM
  - SN Ia-SC
  - SN Ia-pec
  - SN Iax
  - SN Ib
  - SN Ib-pec
  - SN Ib/c
  - SN Ibn
  - SN Ic
  - SN Ic-BL
  - SN Ic-Ca-rich
  - SN Ic-pec
  - SN Icn
  - TDE
  - SN-like
  - CC
  - SN II-gen
  - SN-gen
  - SN Ia-gen
  - SN II-like
  - SN Ib/c-gen
  - SN Ic-gen
  - SN Ib-gen
