create_dirs: true
relative_dirs: true
data_dir: /Users/kdesoto/python_repos/sp-stable/superphot-plus/data/tutorial
transient_data_fn: transients_spec_group
sampler_results_fn: sampler_result_group
sampler: superphot_svi
chisq_cutoff: 1.2
figs_dir: figs
metrics_dir: metrics
fit_plots_dir: fits
cm_dir: confusion_matrices
logging: false
log_fn: results.log
plot: true
load_checkpoint: false
models_dir: models
model_type: MLP
probs_dir: probabilities
input_features: null
use_redshift_features: false
fits_per_majority: 10
target_label: null
prob_threshhold: 0.5
allowed_types:
- SN Ia
- SN Ibc
- SN II
- SN IIn
- SLSN-I
- SN Ibn
neurons_per_layer: 64
num_hidden_layers: 3
learning_rate: 0.001
batch_size: 64
n_folds: 5
num_epochs: 100
n_parallel: 8
random_seed: 42
