data_dir: "/Users/kdesoto/superphot-plus-data"
transient_data_fn: "transients_spec_group"
sampler_results_fn: "sampler_result_group"
sampler: "superphot_svi"
chisq_cutoff: 1.2
plot: True
model_type: "LightGBM"
use_redshift_features: False
fits_per_majority: 5
prob_threshhold: 0.5
n_folds: 10
num_epochs: 250
random_seed: 42
n_parallel: 8
#target_label: None
#input_dim: None
#output_dim: None
#neurons_per_layer: None
#num_hidden_layers: None
#learning_rate: None
#batch_size: None
